# Generated by Django 4.0.5 on 2022-06-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exposure_start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
