# Generated by Django 4.0.5 on 2022-06-21 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_of_exposed_day',
            field=models.DateField(default=datetime.date(2022, 6, 28)),
        ),
    ]
