# Generated by Django 4.0.5 on 2022-06-22 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_end_of_exposed_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_of_exposed_day',
            field=models.DateField(default=datetime.date(2022, 6, 29)),
        ),
    ]
