# Generated by Django 4.0.5 on 2022-06-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contents',
        ),
    ]
