# Generated by Django 4.0.5 on 2022-06-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
